### ISSUE TITLE
deno-pug failed to work on opine

### ISSUE THREAD

**Issue by ngdangtu-vn** [codehz/deno-pug#1]
This is the result when I tried to applied it as a template engine for Deno Opine. Unfortunately, it doesn't work. Here is the result from web browser:

```
function pug_rethrow(e,n,r,t){if(!(e instanceof Error))throw e;if(!("undefined"==typeof window&&n||t))throw e.message+=" on line "+r,e;var o,a,i,s;try{t=t||require("fs").readFileSync(n,{encoding:"utf8"}),o=3,a=t.split("\n"),i=Math.max(r-o,0),s=Math.min(a.length,r+o)}catch(t){return e.message+=" - could not read from "+n+" ("+t.message+")",void pug_rethrow(e,null,r)}o=a.slice(i,s).map(function(e,n){var t=n+i+1;return(t==r?" > ":" ")+t+"| "+e}).join("\n"),e.path=n;try{e.message=(n||"Pug")+":"+r+"\n"+o+"\n\n"+e.message}catch(e){}throw e}function template(locals) {var pug_html = "", pug_mixins = {}, pug_interp;var pug_debug_filename, pug_debug_line;try {;pug_debug_line = 1;pug_debug_filename = "C:\\lalaland\\view\\home.pug"; pug_html = pug_html + "\u003C!DOCTYPE html\u003E"; ;pug_debug_line = 2;pug_debug_filename = "C:\\lalaland\\view\\home.pug"; pug_html = pug_html + "\u003Chtml lang=\"en\"\u003E"; ;pug_debug_line = 3;pug_debug_filename = "C:\\lalaland\\view\\home.pug"; pug_html = pug_html + "\u003Chead\u003E"; ;pug_debug_line = 4;pug_debug_filename = "C:\\lalaland\\view\\home.pug"; pug_html = pug_html + "\u003Cmeta charset=\"UTF-8\"\u003E"; ;pug_debug_line = 5;pug_debug_filename = "C:\\lalaland\\view\\home.pug"; pug_html = pug_html + "\u003Cmeta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\"\u003E"; ;pug_debug_line = 6;pug_debug_filename = "C:\\lalaland\\view\\home.pug"; pug_html = pug_html + "\u003Cmeta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"\u003E"; ;pug_debug_line = 7;pug_debug_filename = "C:\\lalaland\\view\\home.pug"; pug_html = pug_html + "\u003Ctitle\u003E"; ;pug_debug_line = 7;pug_debug_filename = "C:\\lalaland\\view\\home.pug"; pug_html = pug_html + "Manga Reader\u003C\u002Ftitle\u003E\u003C\u002Fhead\u003E"; ;pug_debug_line = 8;pug_debug_filename = "C:\\lalaland\\view\\home.pug"; pug_html = pug_html + "\u003Cbody\u003E"; ;pug_debug_line = 8;pug_debug_filename = "C:\\lalaland\\view\\home.pug"; pug_html = pug_html + " "; ;pug_debug_line = 9;pug_debug_filename = "C:\\lalaland\\view\\home.pug"; pug_html = pug_html + "\u003Cp\u003E"; ;pug_debug_line = 9;pug_debug_filename = "C:\\lalaland\\view\\home.pug"; pug_html = pug_html + "Hello World\u003C\u002Fp\u003E\u003C\u002Fbody\u003E\u003C\u002Fhtml\u003E";} catch (err) {pug_rethrow(err, pug_debug_filename, pug_debug_line);};return pug_html;}
```

If I tried to console.log the `compileFileClient` out, it will be look like this:

```
error: Uncaught Error: The filename, directory name, or volume label syntax is incorrect. (os error 123)
  const data = Deno.readFileSync(path3);
                    ^
    at deno:core/01_core.js:106:46
    at unwrapOpResult (deno:core/01_core.js:126:13)
    at Object.opSync (deno:core/01_core.js:140:12)
    at openSync (deno:runtime/js/40_files.js:37:22)
    at Object.readFileSync (deno:runtime/js/40_read_file.js:10:18)
    at Object.readFileSync (https://cdn.esm.sh/v44/deno_std_node_fs.js:4057:21)
    at S (https://cdn.esm.sh/v44/pug@3.0.2/deno/pug.js:11:152)
    at a.compileFile (https://cdn.esm.sh/v44/pug@3.0.2/deno/pug.js:11:1552)
    at file:///C:/lalaland/server.ts:25:2
```

Here is how I did it:

```TypeScript
export * from 'https://deno.land/x/opine@1.7.1/mod.ts'
import { compileFileClient } from 'https://deno.land/x/pug@v0.1.1/mod.ts'

const viewPath = path.join(path.dirname(import.meta.url), 'view')
app.set('views', viewPath)
app.set('view engine', 'pug')
app.engine('pug', compileFileClient)


const website = new Router()

website.get(
   '/',
   (req, res) => res.render('home')
)

app.use('/', website)


console.log(
    compileFileClient(path.join(viewPath, 'home'))
)
```

My spec:

```
deno         1.12.0+1ad6575,
v8           9.2.230.14,
typescript   4.3.2
deno-pug     0.1.1
opine        1.7.1
```

Did I do something wrong?

**Comment by codehz** [comment]
Ok, can you show the result of the `path.join(viewPath, 'home')`

**Comment by ngdangtu-vn** [comment]
I'm using Windows 10

```
file:\C:\lalaland\view\home
```

`lalaland/` is just a short name for my long path to the root of project. In my root project dir contains server.ts, view/ dir, etc.


Btw, even if I add `pug` extension to `path.join(viewPath, 'home')` , it still returned the same error

**Comment by codehz** [comment]
@ngdangtu-vn you should use file path , not a url, use path.fromFileUrl to convert

**Comment by eevleevs** [comment]
Same here, using file path did not help.
