### ISSUE TITLE
TypeError on Deno Deploy

### ISSUE THREAD

**Issue by eevleevs** [codehz/deno-pug#4]
```
TypeError: Can not modify env vars during execution.
    at Object.setEnv [as set] (ext:deno_deploy/10_env.js:8:9)
    at Object.set (https://cdn.esm.sh/v56/node_process.js:56:16)
    at https://cdn.esm.sh/v56/pug@3.0.2/deno/pug.bundle.js:2:70
```

**Comment by codehz** [comment]
Upgraded esm.sh version, it should working now

**Comment by eevleevs** [comment]
`Deno.readFileSync` is not available either on Deploy, must use `Deno.readFile`.

```
TypeError: Deno.readFileSync is not a function
    at Object.readFileSync (https://deno.land/std@0.177.0/node/_fs/_fs_readFile.ts:35:23)
    at kl (https://esm.sh/v111/pug@3.0.2/deno/pug.bundle.js:86:162)
    at Pe.compileFile (https://esm.sh/v111/pug@3.0.2/deno/pug.bundle.js:86:1571)
    at file:///src/templates.ts:7:101
```

**Comment by codehz** [comment]
you may need to use compile/render instead of compileFile/renderFile (and read source file using deno api)

**Comment by eevleevs** [comment]
Works, thanks 👍
